[workspace]
members = [
    "cluster-config",
    "cluster-node",
    "cluster-node-app",
    "remote-actor",
    "remote-actor-derive",
    "remote-actor-server",
    "actor-registry",
    "node-actor",
    "node-actor-server",
    "http-json-transport"
]