version: "3.9"
services:
  leader:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./cluster-node-app/config.example.json:/etc/config.json
    entrypoint: /usr/bin/cluster-node-app -n 1 --config-file /etc/config.json
    
  follower:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - ./cluster-node-app/config.example.json:/etc/config.json
    entrypoint: /usr/bin/cluster-node-app -n 2 --config-file /etc/config.json